.eslintrc.json, cms/config.js, cms/services.ts, content/example-1.md, content/example-2.md, content/services/test.md, pages/index.tsx
https://trello.com/c/oBfYGqP8/20-list-of-results-vvv-ee
=> 20 list of results

cms/config.js, cms/services.ts, content/services/girls-only-football-coaching-6-a-side.md, content/services/groove-school.md, content/services/test.md, pages/index.tsx, pages/service/[id].tsx, src/Components/Card.tsx, src/Components/CardList.tsx, src/Components/VisuallyHidden.tsx
https://trello.com/c/ZExqH6Tv/37-the-cost-location-and-time-info-are-displayed-on-the-details-view-vvv-ee
Additionally makes all the types be a subset of the main type, so requirement/optionality is also shared
=> 37 cost location and time info

cms/services.ts, pages/service/[id].tsx, src/Components/Card.tsx
https://trello.com/c/CkYfxL3t/34-eligibility-list-item-detail-view-vv-e
=> feat: add eligibility details display

pages/filter.tsx, src/Components/CardList.tsx, src/context/FilterContext.tsx
https://trello.com/c/Y77bYSpX/54-alpha-testing-issues
@roseb04 fixed via VS Code live share:
- Age filter does not work
- It's not clear how to get back to results
- When nothing is selected, all results should come back
- Filter default should be nothing selected
=> fix: age filter function and usability improvements

src/Components/Card.tsx, src/Theme.ts, styled.d.ts
https://trello.com/c/i9KZKHag/72-card-info-vvv-ee
=> feat: new card visual layout

pages/filter.tsx, pages/service/[id].tsx, src/Components/ButtonBase.tsx, src/Components/Card.tsx, src/Components/CardList.tsx, src/Components/Header.tsx, src/context/FilterContext.tsx
https://trello.com/c/75JVbA2A/
This makes the header title slightly off-centre - hopefully that's not a problem. The other option to stop this from happening would be some weird kind of absolute positioning model, which would be a bit messy.
=> refactor: remove categories from filter, consolidate duplicated button styling in one component

pages/service/[id].tsx, src/Components/ButtonBase.tsx, src/Components/FiveStar.tsx
resolves: https://trello.com/c/oVae6bEX/
Looks like:
=> feat: add review section to service page

pages/_app.tsx, pages/filter.tsx, pages/service/[id].tsx, src/Components/Layout.tsx, src/context/NotificationsContext.tsx
https://trello.com/c/09DHlWsF/
No image for this one, just open up the preview and try it out! Spamming the 'submit review' button is quite fun.
Usage is as simple as:
```jsx
import { useContext } from 'react';
import { NotificationsContext } from './context/NotificationsContext';
const MyComponent = () => {
const { notify } = useContext(NotificationsContext);
const clickedNotification = () => {
notify({
msg: "Hello world!",
time: 5000,
});
};
return <button onClick={clickedNotification}>Click me!</button>;
}
```
=> feat: add toast notifications

pages/filter.tsx, pages/index.tsx, pages/quiz/about-you.tsx, pages/quiz/helplines.tsx, pages/quiz/how-are-you-feeling.tsx, pages/quiz/index.tsx, pages/quiz/results.tsx, pages/quiz/what-are-your-interests.tsx, pages/quiz/whats-on-your-mind.tsx, pages/saved.tsx, src/Components/Header.tsx
https://trello.com/c/NsK8FiFN/85-navigation-vv-ee
- I think we'll want to move the filter button closer to the content it relates to
- Same for the quiz questions
=> feat: add header navigation

pages/filter.tsx, pages/index.tsx, pages/quiz/about-you.tsx, pages/quiz/helplines.tsx, pages/quiz/how-are-you-feeling.tsx, pages/quiz/index.tsx, pages/quiz/results.tsx, pages/quiz/what-are-your-interests.tsx, pages/quiz/whats-on-your-mind.tsx, pages/saved.tsx, pages/service/[id].tsx, src/Components/Header.tsx, src/Components/LinkButton.tsx
https://trello.com/c/E5zWLcWZ/108-quiz-navigation
=> 108 quiz navigation

pages/service/[id].tsx
https://trello.com/c/JcNfxzOL/89-display-the-phone-number-v-e
=> feat: display phone number in contact details

src/Components/SaveButton.tsx, src/context/NotificationsContext.tsx, src/context/SaveContext.tsx
https://trello.com/c/IlJaJQfI/115-use-notification-system-for-saving-unsaving-services-v-e
=> feat: use notifications when saving and unsaving services

pages/service/[id].tsx
https://trello.com/c/q4QrH4pc/122-service-review-accessibility
=> fix: review form accessibility

pages/quiz/results.tsx, src/context/QuizContext.tsx
https://trello.com/c/4DyyZLPd/119-save-the-quiz-completed-flag-to-local-storage-vv-e
=> fix: save quiz completed flag to local storage

pages/filter.tsx, pages/index.tsx, pages/quiz/about-you.tsx, pages/quiz/how-are-you-feeling.tsx, pages/quiz/what-are-your-interests.tsx, pages/quiz/whats-on-your-mind.tsx, pages/service/[id].tsx, src/Components/Arrow.tsx, src/Components/CardList.tsx, src/Components/EmptyList.tsx, src/Components/Header.tsx, src/Components/LinkButton.tsx, src/Components/SaveButton.tsx, src/Theme.ts, styled.d.ts
https://trello.com/c/pR1eeDZa/92-make-the-filter-and-results-feel-more-connected-v-e
TODO: Use SVG arrows rather than '<' consistently
=> feat: move filter button closer to results that use it

pages/quiz/how-are-you-feeling.tsx
https://trello.com/c/ffCEpxbw/120-conditional-link-to-helplines-missing
=> feat: go to helplines page if necessary

src/Components/CardList.tsx
https://trello.com/c/bbjg9lz6/126-saved-list-not-filtering 😬
=> fix: save filtering

pages/quiz/helplines.tsx
https://trello.com/c/vXjnl0fP/124-helplines-text-doesnt-make-sense-vv-e
=> fix: helplines text doesn't make sense

pages/_document.tsx
https://trello.com/c/cgE1WBI7/87-feedback-on-the-app-google-analytics-hotjar-plausible-v-ee
=> feat: add analytics script

pages/quiz/about-you.tsx, pages/quiz/how-are-you-feeling.tsx, pages/quiz/what-are-your-interests.tsx, pages/quiz/whats-on-your-mind.tsx, src/Components/CardList.tsx, src/context/QuizContext.tsx
https://trello.com/c/FuYYijAE/127-code-refactor-stronger-typing-v-ee
=> refactor: stronger typing with quiz context

pages/filter.tsx, pages/quiz/about-you.tsx, pages/quiz/what-are-your-interests.tsx, pages/quiz/whats-on-your-mind.tsx, pages/service/[id].tsx, src/Components/Card.tsx, src/Components/CardList.tsx, src/Components/Header.tsx, src/Theme.ts, styled.d.ts
https://trello.com/c/BgS0lLuJ/132-nav-is-squashed-on-smallest-screens
=> fix: use a smaller amount of padding on very small screens

pages/helplines.tsx, src/Components/Header.tsx
https://trello.com/c/tnupEMB9/86-urgent-help-link-vv-ee
From initial feedback, the quiz/helplines content may be moving, so I've just duplicated the current content until we know.
=> feat: add urgent help link and temporary helpline page

cms/config.js, cms/services.ts, pages/index.tsx, pages/quiz/results.tsx, pages/saved.tsx, src/Components/CardList.tsx
https://trello.com/c/DIPyMRJT/83-ability-to-choose-the-first-2-services-users-see-vvv-ee
=> 83 ability to choose the first 2 services users see

src/Components/CardList.tsx, src/Components/CardListNavigation.tsx, src/Components/EmptyList.tsx, src/Components/FilterButton.tsx, src/Components/Header.tsx
Issue: https://trello.com/c/m2vfAe2I/143-move-the-filter-to-above-the-list-of-results-vvv-e
=> Move filter to above the card list

pages/quiz/about-you.tsx, pages/quiz/how-are-you-feeling.tsx, pages/quiz/what-are-your-interests.tsx, pages/quiz/whats-on-your-mind.tsx
https://trello.com/c/IltkMOUd/153-increase-the-visual-hierarchy-of-skip-button-on-quiz-pages-vv-e
=> feat: make it clearer that you can skip questions

cms/config.js, cms/privacy.ts, content/privacy/privacy.md, package.json, pages/privacy-policy.tsx, pages/service/[id].tsx, src/Components/ButtonBase.tsx, src/Components/Checkbox.tsx, src/Components/FiveStar.tsx, src/Theme.ts, styled.d.ts, yarn.lock
https://trello.com/c/Yp8a8XDH/103-gdpr-implications-review-submission-vvv-ee
=> 103 gdpr implications review submission

pages/filter.tsx
https://trello.com/c/nmr2y1Cx/152-back-button-on-filter-vv-e
Other thoughts: 
The filter feels like a modal, we could have a 'close x' in the top right instead of using '< back'
I feel like the back/close option should return to the list without filtering, but since it's not immediately obvious to the user wether the filter has been applied I'm not sure if it matters?
=> 152 back button on filter

pages/filter.tsx
Fixes this card: https://trello.com/c/JuUVHerc/183-move-back-button-on-filter-to-top-left-hand-mobile-vv-e
=> feat: move the location of the close button

src/Components/Bookmark.tsx, src/Components/FiveStar.tsx, src/Components/SaveButton.tsx, src/Components/StickyNavBar.tsx
https://trello.com/c/3PbRTRxb/173-standardise-icons-for-saving-and-rating-vv-ee
=> 173 standardise icons for saving and rating

src/Components/FilterButton.tsx
https://trello.com/c/LNnUEtXK/167-display-current-filters-vv-ee
=> feat: add active filters indicator

src/Components/Burger.tsx, src/Components/Header.tsx, src/Components/Menu.tsx, src/hooks/useOnClickOutside.tsx
https://trello.com/c/YvUc6nEt/172-add-hamburger-menu-in-header-vvv-ee
=> 172 add menu in header

pages/filter.tsx, src/Components/CardList.tsx, src/Components/Checkbox.tsx, src/Components/RadioButton.tsx, src/context/FilterContext.tsx
https://trello.com/c/4oecr4z8/182-style-filter-mobile-vv
=> 182 style filter mobile

cms/config.js, package.json, pages/filter.tsx, pages/quiz/about-you.tsx, pages/service/[id].tsx, src/Components/CardList.tsx, src/context/FilterContext.tsx, yarn.lock
https://trello.com/c/yhklwJ8q/175-update-dependencies-vvv-ee
=> feat: upgrade to React 17 and Next 10.2

src/Components/QuizEncouragement.tsx
https://trello.com/c/tJLAfPk2/179-make-quiz-clickable-and-style-v-ee
=> feat: make quiz call to action clickable and style

src/Components/EmptyList.tsx
https://trello.com/c/hwxy0GmA/199-update-saved-icon-on-saved-page
=> fix: replace star icon with bookmark

pages/cookies.tsx
https://trello.com/c/k4ZnyXxc/204-successfully-saving-changes-on-cookies-page-needs-some-sort-of-confirmation-alert-action
=> feat: add notification for saving cookie prefs

src/Components/CookieBanner.tsx
https://trello.com/c/qZdnWZtD/202-cookies-banner-keyboard-controls
Couldn't tab or see focus using ButtonBase as button so replaced with styled button
=> fix: cookie button keyboard focus

cms/about.ts, cms/config.js, content/about/about.md, pages/404.tsx, pages/about.tsx, src/Components/Menu.tsx
https://trello.com/c/WBbYL6kl/201-add-about-page-and-connect-to-cms-link-to-other-pages
=> 201 add about page and 404

.eslintignore, pages/api/_lib/oauth2.ts, src/context/QuizContext.tsx
https://trello.com/c/oqCecyzH/206-pwa-linting-errors
=> fix: eslint warnings

pages/privacy-policy.tsx
https://trello.com/c/XLhvkZNm/209-no-link-to-cookies-page-on-desktop
=> feat: add link to manage cookies on privacy policy

src/Components/Burger.tsx, src/Components/DesktopNav.tsx, src/Components/Welcome.tsx
https://trello.com/c/XDPTAlMY/203-responsive-styling-for-welcome-screens
=> 203 responsive styling for welcome screens

pages/service/[id].tsx, src/Components/EmptyList.tsx
https://trello.com/c/8wnHeun5/164-xxx-copy-sweep
=> feat: remove all temporary copy markers

pages/_app.tsx
https://trello.com/c/9JSPe3wv/192-setup-the-ability-to-track-the-number-of-visits-a-user-has-to-the-site-with-hotjar-v-e
=> feat: return user tracking

pages/helplines.tsx, src/Components/CardList.tsx
https://trello.com/c/UKK7vps5/213-update-urgent-help-to-the-styling-used-in-the-quiz-version
=> 213 update urgent help

src/Components/Burger.tsx
https://trello.com/c/ytxG9OQu/221-menu-button-missing-on-iphone
=> fix: add appearance property for Safari

pages/_app.tsx, pages/_document.tsx
Updates Hotjar id and Plausible domain to production
=> feat: set analytics to production sites

pages/_app.tsx
Fix this: https://trello.com/c/88Cy9Hr8/225-update-hotjar-with-new-tracking-code
=> Update with new hotjar tracking code

README.md, cms/config.js
https://trello.com/c/CTfhdpud/249-set-cms-to-edit-staging-and-workflow
=> feat: update CMS target branch and add content workflow docs

cms/services.ts, fixtures/MBL area covered.csv
https://trello.com/c/dk2FnNCb/233-building-csvs-into-services
This should add the remaining fields:
- Interests
- Areas
- Data provider
=> feat: add provider, interest and area data from fixtures

README.md
https://trello.com/c/OWt07Mpq/247-promoting-staging-to-live
=> feat: add deployment documentation

pages/_document.tsx
https://trello.com/c/cC7eCr20/243-tracking-and-analytics
=> fix: use new plausible script

content/services/elays-network-elays-youth-club-general-youth-club.md, content/services/game-of-two-halves-programme.md, content/services/i-am-in-me-business-start-up.md, content/services/mtvh-metropolitan-thames-valley-housing-11444.md
https://trello.com/c/uLt7LUje/242-data-changes-to-match-fid
Some locations seem to have been missed / overwritten - this should match them to the current filter
=> fix: update missing locations

content/services/allstars-activity-club-ltd-11406.md, content/services/allstars-activity-club-ltd-11459.md, content/services/ashdon-jazz-academy-11529.md, content/services/bigkid-foundation-11516.md, content/services/black-prince-community-trust-11409.md, content/services/coin-street-community-builders-limited-11447.md, content/services/creative-sparkworks-11449.md, content/services/grove-adventure-playground-11452.md, content/services/high-trees-community-development-trust-11513.md, content/services/katakata-11524.md, content/services/learn-interact-trade-capital-ltd-11520.md, content/services/lerato-community-initiative-11515.md, content/services/marcus-lipton-community-enterprise-ltd-11441.md, content/services/rathbone-society-11521.md, content/services/rising-stars-support-11518.md, content/services/slade-gardens-community-play-association-11429.md, content/services/step-now-11522.md, content/services/streamz-11517.md, content/services/streatham-academy-football-club-11426.md, content/services/street-soccer-london-11519.md, content/services/the-hebe-foundation-11523.md, content/services/uincap-international-union-of-capoeira-11420.md, content/services/uincap-international-union-of-capoeira-11421.md, content/services/upper-norwood-library-trust-11514.md
https://trello.com/c/EoRs5ut0/235-fetching-data-from-fid
=> feat: add new services

pages/cookies.tsx
Access /cookies page to see the save button
Trello Card - [https://trello.com/c/RgexBgl6/251-fid-release-testing-issues](https://trello.com/c/RgexBgl6/251-fid-release-testing-issues)
=> fix: spacing below save changes button added

content/services/the-hebe-foundation-11548.md, content/services/willington-road-youth-community-hub-11530.md
https://trello.com/c/EoRs5ut0/235-fetching-data-from-fid
=> fix: add new service
